# docker compose -f docker-compose.yml up --build -d
# docker compose -f docker-compose.yml down -v

# docker exec -it container bash
version: '1.0'

services:
  navilos:
    container_name: container
    image: navilos
    tty: true
    privileged: true
    build: .
    ports:
      - '9999:9999'
    volumes:
      - '.:/app'
      - 'volume:/app'

volumes:
  volume: